// Mocks generated by Mockito 5.4.4 from annotations
// in iaso/test/medication_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:iaso/data/med_repository.dart' as _i2;
import 'package:iaso/domain/medication.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MedRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedRepository extends _i1.Mock implements _i2.MedRepository {
  MockMedRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Medication>> getMedications() => (super.noSuchMethod(
        Invocation.method(
          #getMedications,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.Medication>>.empty(),
      ) as _i3.Stream<List<_i4.Medication>>);

  @override
  _i3.Future<List<_i4.Medication>> getMedicationsList() => (super.noSuchMethod(
        Invocation.method(
          #getMedicationsList,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Medication>>.value(<_i4.Medication>[]),
      ) as _i3.Future<List<_i4.Medication>>);

  @override
  _i3.Future<void> addMedication(_i4.Medication? medication) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMedication,
          [medication],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateMedication(_i4.Medication? medication) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMedication,
          [medication],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMedication(String? medicationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMedication,
          [medicationId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
